In [1]:
import stock_data
import twitter_data

In [2]:
import os
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.utils import to_categorical
from tensorflow.keras.layers import Dense
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from tensorflow.keras.models import Sequential

In [58]:
from sklearn import svm

In [128]:
companies = ['Apple Inc', 'Microsoft Corporation', 'YELP INC', 'Google INC', 'UBER TECHNOLOGIES INC', 'Starbucks Corporation', 'Ford Motor Co', 'Facebook Inc', 'Twitter Inc', 'Berkshire Hathaway Inc.', 'Tyson Foods, Inc.', 'ArQule Inc.']


In [129]:
data5 = twitter_data.data_creator_binary(companies)

/Users/PatBeljan/Desktop/Bootcamp/final_project/twitter_data.py:229: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  stock['Date'] = stock['Date'].astype('str')
/Users/PatBeljan/Desktop/Bootcamp/final_project/twitter_data.py:229: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  stock['Date'] = stock['Date'].astype('str')
/Users/PatBeljan/Desktop/Bootcamp/final_project/twitter_data.py:229: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the ca

In [88]:
data3

Unnamed: 0  negative  positive  total  Price Change_down  Price Change_up
0            0  0.219251  0.272727  187.0                  0                1
1            1  0.157025  0.396694  121.0                  0                1
2            2  0.080000  0.700000  200.0                  1                0
3            3  0.049587  0.165289  242.0                  1                0
4            4  0.101266  0.208861  158.0                  0                1
5            0  0.057143  0.371429   35.0                  1                0
6            1  0.094595  0.256757   74.0                  0                1
7            2  0.200000  0.240000   50.0                  1                0
8            3  0.122449  0.367347   49.0                  0                1
9            4  0.181818  0.318182   22.0                  0                1
10           0  0.000000  0.555556    9.0                  0                1
11           1  0.000000  0.961538   26.0                  0                1
12           2  0.000000  0.625000    8.0                  0                1
13           3  0.568182  0.113636   44.0                  0                1
14           4  0.568182  0.113636   44.0                  0                1
15           0  0.080000  0.565000  200.0                  0                1
16           1  0.064516  0.322581  155.0                  0                1
17           2  0.035000  0.120000  200.0                  1                0
18           3  0.025253  0.373737  198.0                  0                1
19           4  0.244681  0.393617   94.0                  0                1
20           0  0.041667  0.000000  120.0                  0                1
21           1  0.000000  0.444444    9.0                  0                1
22           2  0.304348  0.043478   23.0                  0                1
23           3  0.125000  0.250000    8.0                  0                1
24           4  0.666667  0.222222    9.0                  1                0
25           0  0.230769  0.461538   13.0                  1                0
26           1  0.666667  0.333333    6.0                  0                1
27           2  0.000000  0.909091   66.0                  1                0
28           3  0.000000  0.923077   26.0                  0                1
29           4  0.125000  0.750000    8.0                  0                1
30           0  0.000000  0.545455   22.0                  1                0
31           1  0.025641  0.307692   39.0                  1                0
32           2  0.076923  0.153846   26.0                  0                1
33           3  0.629630  0.037037   27.0                  1                0
34           4  0.400000  0.200000    5.0                  0                1
35           0  0.086705  0.341040  173.0                  1                0
36           1  0.081522  0.320652  184.0                  0                1
37           2  0.086207  0.267241  116.0                  1                0
38           3  0.080645  0.295699  186.0                  0                1
39           4  0.210526  0.324561  114.0                  0                1
40           0  0.042328  0.201058  189.0                  1                0
41           1  0.090000  0.266667  300.0                  1                0
42           2  0.050000  0.260000  200.0                  0                1
43           3  0.056667  0.380000  300.0                  0                1
44           4  0.075377  0.266332  199.0                  0                1

In [132]:
data5.reset_index(inplace=True)

In [168]:
data5.to_csv('training_data.csv')

In [139]:
data6x = []
data6y = []
for i in range(0, len(data5)-5,5):
    try:
        tempx = np.array([])
        tempy = np.array([])
        negative = data5.iloc[i,1] + data5.iloc[i+1,1] + data5.iloc[i+2,1] + data5.iloc[i+3,1] + data5.iloc[i+4,1] 
        positive = data5.iloc[i,2] + data5.iloc[i+1,2] + data5.iloc[i+2,2] + data5.iloc[i+3,2] + data5.iloc[i+4,2]
        up_sum = data5.iloc[i,5] + data5.iloc[i+1,5] + data5.iloc[i+2,5] + data5.iloc[i+3,5] + data5.iloc[i+4,5]
        if up_sum > 2:
            change = 1
        else:
            change = 0
        tempx = np.append(tempx, [negative, positive])
        data6x.append(tempx)
        tempy = np.append(tempy,[change])
        data6y.append(tempy)
    except:
        print(i)

In [140]:
data6x = np.asarray(data6x)
data6y = np.asarray(data6y)

In [141]:
data6x

array([[0.91221833, 1.75215763],
       [0.6131379 , 1.52368464],
       [0.96818182, 2.45847763],
       [0.31245742, 2.03584426],
       [1.02686335, 0.95220842],
       [1.0224359 , 3.37703963],
       [0.9011529 , 1.42572293],
       [0.35060131, 1.75027643],
       [0.3488813 , 1.69110366],
       [0.        , 2.79100529],
       [1.16666667, 0.66666667],
       [1.33333333, 0.93333333]])

In [142]:
data6y

array([[1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [0.],
       [1.],
       [1.],
       [0.],
       [0.],
       [0.]])

In [ ]:
data.head()

In [ ]:
data2.head()

In [3]:
data3 = pd.read_csv('training_data.csv')

In [87]:
data5

negative  positive  total  Price Change_down  Price Change_up
0       0.0  0.000000    4.0                  1                0
1       0.0  0.000000    1.0                  0                1
2       0.0  0.500000    2.0                  0                1
3       0.0  0.000000    0.0                  1                0
4       0.0  1.000000    1.0                  1                0
0       0.0  0.000000    1.0                  1                0
1       0.0  0.000000    0.0                  0                1
2       0.5  0.000000    4.0                  1                0
3       0.4  0.000000    5.0                  1                0
4       0.0  0.166667    6.0                  0                1
0       0.0  0.000000    0.0                  1                0
1       0.0  0.000000    0.0                  0                1
2       0.0  0.000000    3.0                  0                1
3       0.0  0.000000    0.0                  0                1
4       0.0  0.000000    0.0                  0                1

In [63]:
data4 = data3.loc[data3['total'] >= 100]

In [69]:
data4

Unnamed: 0  negative  positive  total  Price Change_down  Price Change_up
0            0  0.219251  0.272727  187.0                  0                1
1            1  0.157025  0.396694  121.0                  0                1
2            2  0.080000  0.700000  200.0                  1                0
3            3  0.049587  0.165289  242.0                  1                0
4            4  0.101266  0.208861  158.0                  0                1
15           0  0.080000  0.565000  200.0                  0                1
16           1  0.064516  0.322581  155.0                  0                1
17           2  0.035000  0.120000  200.0                  1                0
18           3  0.025253  0.373737  198.0                  0                1
20           0  0.041667  0.000000  120.0                  0                1
35           0  0.086705  0.341040  173.0                  1                0
36           1  0.081522  0.320652  184.0                  0                1
37           2  0.086207  0.267241  116.0                  1                0
38           3  0.080645  0.295699  186.0                  0                1
39           4  0.210526  0.324561  114.0                  0                1
40           0  0.042328  0.201058  189.0                  1                0
41           1  0.090000  0.266667  300.0                  1                0
42           2  0.050000  0.260000  200.0                  0                1
43           3  0.056667  0.380000  300.0                  0                1
44           4  0.075377  0.266332  199.0                  0                1

In [4]:
from numpy.random import seed
seed(42)

In [143]:
X = data6x#data4[['negative']].values
y = data6y#data4[['Price Change_down']].values

In [52]:
y

array([[0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [0],
       [0]])

In [144]:
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=1)

In [174]:
X_train

array([[1.16666667, 0.66666667],
       [0.6131379 , 1.52368464],
       [0.9011529 , 1.42572293],
       [0.91221833, 1.75215763],
       [0.35060131, 1.75027643],
       [1.33333333, 0.93333333],
       [0.        , 2.79100529],
       [0.3488813 , 1.69110366],
       [1.0224359 , 3.37703963]])

In [145]:
X_scaler = StandardScaler().fit(X_train)
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

StandardScaler(copy=True, with_mean=True, with_std=True)

In [80]:
X_train_scaled

array([[ 2.07790857],
       [ 0.20176752],
       [-0.67853159],
       [-0.93610058],
       [ 1.15921967],
       [-0.15231535],
       [ 2.22772824],
       [-0.24277834],
       [-0.56405648],
       [-0.82162547],
       [-0.81026882],
       [-1.10347707],
       [-0.05681331],
       [-0.1372634 ],
       [-0.16339359]])

In [146]:
model2 = Sequential()

number_inputs = 2
number_hidden_nodes = 4
model2.add(Dense(units=number_hidden_nodes,activation='relu', input_dim=number_inputs))

number_classes = 2
model2.add(Dense(units=number_classes, activation='softmax'))

In [147]:
model2.summary()

Model: "sequential_8"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_16 (Dense)             (None, 4)                 12        
_________________________________________________________________
dense_17 (Dense)             (None, 2)                 10        
Total params: 22
Trainable params: 22
Non-trainable params: 0
_________________________________________________________________


In [148]:
model2.compile(optimizer='adam', loss='categorical_crossentropy',metrics=['accuracy'])

In [149]:
y_train_categorical = to_categorical(y_train)
y_test_categorical = to_categorical(y_test)

In [150]:
model2.fit(
    X_train,
    y_train_categorical,
    epochs=1000,
    shuffle=True,
    verbose=2
)

Train on 9 samples
Epoch 1/1000
9/9 - 0s - loss: 0.8454 - accuracy: 0.4444
Epoch 2/1000
9/9 - 0s - loss: 0.8428 - accuracy: 0.4444
Epoch 3/1000
9/9 - 0s - loss: 0.8402 - accuracy: 0.4444
Epoch 4/1000
9/9 - 0s - loss: 0.8377 - accuracy: 0.4444
Epoch 5/1000
9/9 - 0s - loss: 0.8352 - accuracy: 0.4444
Epoch 6/1000
9/9 - 0s - loss: 0.8326 - accuracy: 0.4444
Epoch 7/1000
9/9 - 0s - loss: 0.8302 - accuracy: 0.4444
Epoch 8/1000
9/9 - 0s - loss: 0.8277 - accuracy: 0.4444
Epoch 9/1000
9/9 - 0s - loss: 0.8252 - accuracy: 0.4444
Epoch 10/1000
9/9 - 0s - loss: 0.8228 - accuracy: 0.4444
Epoch 11/1000
9/9 - 0s - loss: 0.8204 - accuracy: 0.4444
Epoch 12/1000
9/9 - 0s - loss: 0.8181 - accuracy: 0.4444
Epoch 13/1000
9/9 - 0s - loss: 0.8157 - accuracy: 0.4444
Epoch 14/1000
9/9 - 0s - loss: 0.8134 - accuracy: 0.4444
Epoch 15/1000
9/9 - 0s - loss: 0.8111 - accuracy: 0.4444
Epoch 16/1000
9/9 - 0s - loss: 0.8088 - accuracy: 0.4444
Epoch 17/1000
9/9 - 0s - loss: 0.8065 - accuracy: 0.4444
Epoch 18/1000
9/9 - 0

Epoch 144/1000
9/9 - 0s - loss: 0.6541 - accuracy: 0.6667
Epoch 145/1000
9/9 - 0s - loss: 0.6537 - accuracy: 0.6667
Epoch 146/1000
9/9 - 0s - loss: 0.6534 - accuracy: 0.6667
Epoch 147/1000
9/9 - 0s - loss: 0.6530 - accuracy: 0.6667
Epoch 148/1000
9/9 - 0s - loss: 0.6527 - accuracy: 0.6667
Epoch 149/1000
9/9 - 0s - loss: 0.6523 - accuracy: 0.6667
Epoch 150/1000
9/9 - 0s - loss: 0.6520 - accuracy: 0.6667
Epoch 151/1000
9/9 - 0s - loss: 0.6517 - accuracy: 0.6667
Epoch 152/1000
9/9 - 0s - loss: 0.6513 - accuracy: 0.6667
Epoch 153/1000
9/9 - 0s - loss: 0.6510 - accuracy: 0.6667
Epoch 154/1000
9/9 - 0s - loss: 0.6507 - accuracy: 0.6667
Epoch 155/1000
9/9 - 0s - loss: 0.6503 - accuracy: 0.6667
Epoch 156/1000
9/9 - 0s - loss: 0.6500 - accuracy: 0.6667
Epoch 157/1000
9/9 - 0s - loss: 0.6497 - accuracy: 0.6667
Epoch 158/1000
9/9 - 0s - loss: 0.6494 - accuracy: 0.6667
Epoch 159/1000
9/9 - 0s - loss: 0.6491 - accuracy: 0.6667
Epoch 160/1000
9/9 - 0s - loss: 0.6488 - accuracy: 0.6667
Epoch 161/1000

9/9 - 0s - loss: 0.5924 - accuracy: 0.7778
Epoch 286/1000
9/9 - 0s - loss: 0.5918 - accuracy: 0.7778
Epoch 287/1000
9/9 - 0s - loss: 0.5912 - accuracy: 0.8889
Epoch 288/1000
9/9 - 0s - loss: 0.5906 - accuracy: 0.8889
Epoch 289/1000
9/9 - 0s - loss: 0.5900 - accuracy: 0.8889
Epoch 290/1000
9/9 - 0s - loss: 0.5894 - accuracy: 0.8889
Epoch 291/1000
9/9 - 0s - loss: 0.5889 - accuracy: 0.8889
Epoch 292/1000
9/9 - 0s - loss: 0.5883 - accuracy: 0.8889
Epoch 293/1000
9/9 - 0s - loss: 0.5878 - accuracy: 0.8889
Epoch 294/1000
9/9 - 0s - loss: 0.5873 - accuracy: 0.8889
Epoch 295/1000
9/9 - 0s - loss: 0.5868 - accuracy: 0.8889
Epoch 296/1000
9/9 - 0s - loss: 0.5863 - accuracy: 0.8889
Epoch 297/1000
9/9 - 0s - loss: 0.5857 - accuracy: 0.8889
Epoch 298/1000
9/9 - 0s - loss: 0.5852 - accuracy: 0.8889
Epoch 299/1000
9/9 - 0s - loss: 0.5847 - accuracy: 0.8889
Epoch 300/1000
9/9 - 0s - loss: 0.5842 - accuracy: 0.8889
Epoch 301/1000
9/9 - 0s - loss: 0.5837 - accuracy: 0.8889
Epoch 302/1000
9/9 - 0s - los

Epoch 427/1000
9/9 - 0s - loss: 0.5296 - accuracy: 0.8889
Epoch 428/1000
9/9 - 0s - loss: 0.5292 - accuracy: 0.8889
Epoch 429/1000
9/9 - 0s - loss: 0.5289 - accuracy: 0.8889
Epoch 430/1000
9/9 - 0s - loss: 0.5285 - accuracy: 0.8889
Epoch 431/1000
9/9 - 0s - loss: 0.5281 - accuracy: 0.8889
Epoch 432/1000
9/9 - 0s - loss: 0.5277 - accuracy: 0.8889
Epoch 433/1000
9/9 - 0s - loss: 0.5273 - accuracy: 0.8889
Epoch 434/1000
9/9 - 0s - loss: 0.5269 - accuracy: 0.8889
Epoch 435/1000
9/9 - 0s - loss: 0.5266 - accuracy: 0.8889
Epoch 436/1000
9/9 - 0s - loss: 0.5262 - accuracy: 0.8889
Epoch 437/1000
9/9 - 0s - loss: 0.5258 - accuracy: 0.8889
Epoch 438/1000
9/9 - 0s - loss: 0.5254 - accuracy: 0.8889
Epoch 439/1000
9/9 - 0s - loss: 0.5250 - accuracy: 0.8889
Epoch 440/1000
9/9 - 0s - loss: 0.5247 - accuracy: 0.8889
Epoch 441/1000
9/9 - 0s - loss: 0.5243 - accuracy: 0.8889
Epoch 442/1000
9/9 - 0s - loss: 0.5239 - accuracy: 0.8889
Epoch 443/1000
9/9 - 0s - loss: 0.5236 - accuracy: 0.8889
Epoch 444/1000

9/9 - 0s - loss: 0.4822 - accuracy: 0.8889
Epoch 569/1000
9/9 - 0s - loss: 0.4819 - accuracy: 0.8889
Epoch 570/1000
9/9 - 0s - loss: 0.4816 - accuracy: 0.8889
Epoch 571/1000
9/9 - 0s - loss: 0.4814 - accuracy: 0.8889
Epoch 572/1000
9/9 - 0s - loss: 0.4811 - accuracy: 0.8889
Epoch 573/1000
9/9 - 0s - loss: 0.4808 - accuracy: 0.8889
Epoch 574/1000
9/9 - 0s - loss: 0.4805 - accuracy: 0.8889
Epoch 575/1000
9/9 - 0s - loss: 0.4802 - accuracy: 0.8889
Epoch 576/1000
9/9 - 0s - loss: 0.4799 - accuracy: 0.8889
Epoch 577/1000
9/9 - 0s - loss: 0.4796 - accuracy: 0.8889
Epoch 578/1000
9/9 - 0s - loss: 0.4793 - accuracy: 0.8889
Epoch 579/1000
9/9 - 0s - loss: 0.4790 - accuracy: 0.8889
Epoch 580/1000
9/9 - 0s - loss: 0.4788 - accuracy: 0.8889
Epoch 581/1000
9/9 - 0s - loss: 0.4785 - accuracy: 0.8889
Epoch 582/1000
9/9 - 0s - loss: 0.4782 - accuracy: 0.8889
Epoch 583/1000
9/9 - 0s - loss: 0.4779 - accuracy: 0.8889
Epoch 584/1000
9/9 - 0s - loss: 0.4776 - accuracy: 0.8889
Epoch 585/1000
9/9 - 0s - los

Epoch 710/1000
9/9 - 0s - loss: 0.4483 - accuracy: 0.8889
Epoch 711/1000
9/9 - 0s - loss: 0.4481 - accuracy: 0.8889
Epoch 712/1000
9/9 - 0s - loss: 0.4479 - accuracy: 0.8889
Epoch 713/1000
9/9 - 0s - loss: 0.4477 - accuracy: 0.8889
Epoch 714/1000
9/9 - 0s - loss: 0.4475 - accuracy: 0.8889
Epoch 715/1000
9/9 - 0s - loss: 0.4473 - accuracy: 0.8889
Epoch 716/1000
9/9 - 0s - loss: 0.4471 - accuracy: 0.8889
Epoch 717/1000
9/9 - 0s - loss: 0.4469 - accuracy: 0.8889
Epoch 718/1000
9/9 - 0s - loss: 0.4467 - accuracy: 0.8889
Epoch 719/1000
9/9 - 0s - loss: 0.4466 - accuracy: 0.8889
Epoch 720/1000
9/9 - 0s - loss: 0.4464 - accuracy: 0.8889
Epoch 721/1000
9/9 - 0s - loss: 0.4462 - accuracy: 0.8889
Epoch 722/1000
9/9 - 0s - loss: 0.4460 - accuracy: 0.8889
Epoch 723/1000
9/9 - 0s - loss: 0.4458 - accuracy: 0.8889
Epoch 724/1000
9/9 - 0s - loss: 0.4456 - accuracy: 0.8889
Epoch 725/1000
9/9 - 0s - loss: 0.4454 - accuracy: 0.8889
Epoch 726/1000
9/9 - 0s - loss: 0.4453 - accuracy: 0.8889
Epoch 727/1000

Epoch 852/1000
9/9 - 0s - loss: 0.4258 - accuracy: 0.8889
Epoch 853/1000
9/9 - 0s - loss: 0.4257 - accuracy: 0.8889
Epoch 854/1000
9/9 - 0s - loss: 0.4256 - accuracy: 0.8889
Epoch 855/1000
9/9 - 0s - loss: 0.4254 - accuracy: 0.8889
Epoch 856/1000
9/9 - 0s - loss: 0.4253 - accuracy: 0.8889
Epoch 857/1000
9/9 - 0s - loss: 0.4252 - accuracy: 0.8889
Epoch 858/1000
9/9 - 0s - loss: 0.4251 - accuracy: 0.8889
Epoch 859/1000
9/9 - 0s - loss: 0.4249 - accuracy: 0.8889
Epoch 860/1000
9/9 - 0s - loss: 0.4248 - accuracy: 0.8889
Epoch 861/1000
9/9 - 0s - loss: 0.4247 - accuracy: 0.8889
Epoch 862/1000
9/9 - 0s - loss: 0.4246 - accuracy: 0.8889
Epoch 863/1000
9/9 - 0s - loss: 0.4244 - accuracy: 0.8889
Epoch 864/1000
9/9 - 0s - loss: 0.4243 - accuracy: 0.8889
Epoch 865/1000
9/9 - 0s - loss: 0.4242 - accuracy: 0.8889
Epoch 866/1000
9/9 - 0s - loss: 0.4241 - accuracy: 0.8889
Epoch 867/1000
9/9 - 0s - loss: 0.4239 - accuracy: 0.8889
Epoch 868/1000
9/9 - 0s - loss: 0.4238 - accuracy: 0.8889
Epoch 869/1000

9/9 - 0s - loss: 0.4106 - accuracy: 0.8889
Epoch 994/1000
9/9 - 0s - loss: 0.4106 - accuracy: 0.8889
Epoch 995/1000
9/9 - 0s - loss: 0.4105 - accuracy: 0.8889
Epoch 996/1000
9/9 - 0s - loss: 0.4104 - accuracy: 0.8889
Epoch 997/1000
9/9 - 0s - loss: 0.4103 - accuracy: 0.8889
Epoch 998/1000
9/9 - 0s - loss: 0.4102 - accuracy: 0.8889
Epoch 999/1000
9/9 - 0s - loss: 0.4101 - accuracy: 0.8889
Epoch 1000/1000
9/9 - 0s - loss: 0.4100 - accuracy: 0.8889


In [ ]:
y_test

In [ ]:
X_test_scaled

In [ ]:
y_test

In [151]:
model_loss, model_accuracy = model2.evaluate(
    X_test, y_test_categorical, verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

3/3 - 0s - loss: 0.9044 - accuracy: 0.6667
Loss: 0.9044408798217773, Accuracy: 0.6666666865348816


In [ ]:
data10 = data

In [ ]:
test = data3.iloc[0]

In [ ]:
test_x = test[['negative', 'positive', 'total']].values
test_y = test[['Price Change_down', 'Price Change_up']].values

In [ ]:
X_train_scaled2 = X_scaler.transform(np.asarray([test_x]))
#X_test_scaled2 = X_scaler.transform(X_test)

In [ ]:
test_x1 = np.asarray([test_x])
test_y1 = np.asarray([test_y])

In [ ]:
X_train_scaled2

In [ ]:
test_y

In [160]:
X_train_scaled

array([[ 1.0353108 , -1.38030905],
       [-0.30379654, -0.30609278],
       [ 0.39297484, -0.42888141],
       [ 0.41974453, -0.01971674],
       [-0.93893004, -0.0220747 ],
       [ 1.43851398, -1.04605973],
       [-1.78711142,  1.28241122],
       [-0.94309113, -0.09624393],
       [ 0.68638498,  2.01696714]])

In [164]:
y_train

array([[0.],
       [1.],
       [0.],
       [1.],
       [1.],
       [0.],
       [0.],
       [1.],
       [1.]])

In [180]:
model2.evaluate(X_train_scaled, y_train_categorical, verbose = 2)

9/9 - 0s - loss: 0.4984 - accuracy: 0.7778


[0.4984494745731354, 0.7777778]

In [185]:
np.asarray([X_test_scaled[0]])

array([[0.55513248, 0.86560943]])

In [187]:
model2.predict_classes(np.asarray([X_test_scaled[1]]))

array([1])

In [171]:
model2.save('Twitter_Sentiment_Stock_Model.h5')

In [83]:
clf = svm.SVC()
clf.fit(X_train_scaled, y_train)

/anaconda3/lib/python3.7/site-packages/sklearn/utils/validation.py:761: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


AttributeError: 'SVC' object has no attribute 'plot'

In [82]:
clf.predict(X_test_scaled)

array([0, 0, 0, 0, 0])